apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wikiapiary
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/semantisch/wikiapiary-canasta-k8s.git
    targetRevision: main
    path: charts/canasta
    helm:
      releaseName: canasta-wikiapiary-live
      valueFiles:
        - ../../values/prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: canasta-wikiapiary-live
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
