{{- if .Values.configData.web }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "canasta.fullname" . }}-web-config
  namespace: {{ include "canasta.namespace" . }}
  labels:
    {{- include "canasta.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
data:
  {{- $primaryHost := include "canasta.primaryHost" . }}
  {{- $siteServer := include "canasta.siteServer" . }}
  {{- $siteHostsCsv := include "canasta.hostsCsv" . }}
  {{- range $key, $value := .Values.configData.web }}
  {{ $key }}: |
    {{- $value | replace "__PRIMARY_HOST__" $primaryHost | replace "__SITE_SERVER__" $siteServer | replace "__SITE_HOSTS_CSV__" $siteHostsCsv | nindent 4 }}
  {{- end }}
{{- end }}
