{{- if .Values.phpSessions.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "canasta.fullname" . }}-php-sessions
  namespace: {{ include "canasta.namespace" . }}
  labels:
    {{- include "canasta.labels" . | nindent 4 }}
data:
  99-wikiapiary-sessions.ini: |
    session.save_handler = redis
    session.save_path = "tcp://{{ .Values.phpSessions.redisHost }}:{{ .Values.phpSessions.redisPort }}?database={{ .Values.phpSessions.redisDatabase }}&prefix={{ .Values.phpSessions.redisPrefix }}"
    session.use_strict_mode = 1
    session.cookie_httponly = 1
    session.cookie_samesite = Lax
{{- end }}
