apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "canasta.fullname" . }}-varnish-config
  namespace: {{ include "canasta.namespace" . }}
  labels:
    {{- include "canasta.labels" . | nindent 4 }}
    app.kubernetes.io/component: varnish
data:
  {{- $primaryHost := include "canasta.primaryHost" . }}
  {{- if .Values.configData.varnish }}
  {{- range $key, $value := .Values.configData.varnish }}
  {{ $key }}: |
    {{- $value | replace "__PRIMARY_HOST__" $primaryHost | nindent 4 }}
  {{- end }}
  {{- else }}
  default.vcl: |
    {{- .Files.Get "files/default.vcl" | replace "__PRIMARY_HOST__" $primaryHost | nindent 4 }}
  {{- end }}
